FROM ubuntu:22.04


RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y nginx iproute2 netcat-traditional socat vim

COPY files/target-entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT /entrypoint.sh